// word frequencies of first two chapters of Oliver Twist
var words = [
  {text: '수기수기', size: 50},
  {text: 'ㅎㄹ', size: 47},
  {text: 'ㅎㄹㅇ', size: 46},
  {text: 'sa키id', size: 36},
  {text: 'bu키mble', size: 29, href: 'https://en.wikipedia.org/wiki/Beadle'},
  {text: 'wi키ll', size: 29},
  {text: 'Mr키s', size: 56, href: 'https://en.wikipedia.org/wiki/Mrs.'},
  {text: 'Ma키nn', size: 27, href: 'http://educationcing.blogspot.nl/2012/06/oliver-twist-mrs-manns-character.html'},
  {text: 'M키r', size: 27},
  {text: 've키ry', size: 26},
  {text: 'ch키ild', size: 20},
  {text: 'al키l', size: 19},
  {text: 'bo키y', size: 19},
  {text: 'ge키ntleman', size: 19, href: 'http://www.thefreelibrary.com/The+gentleman+in+the+white+waistcoat%3a+Dickens+and+metonymy.-a0154239625'},
  {text: 'gre키at', size: 19},
  {text: 'ta키ke', size: 19},
  {text: 'bu키t', size: 18},
  {text: 'be키adle', size: 16},
  {text: 'tw키ist', size: 16},
  {text: 'bo키ard', size: 15},
  {text: 'mo키re', size: 15},
  {text: 'o키e', size: 15},
  {text: 'wo키rkhouse', size: 15},
  {text: 'pa키rish', size: 14},
  {text: 't키h키ere', size: 14}
];
